package algos03.test;
// Generated by ComTest BEGIN
import static org.junit.Assert.*;
import org.junit.*;
import static algos03.RecursionBiggest.*;
// Generated by ComTest END

/**
 * Test class made by ComTest
 * @version 2022.04.24 15:59:27 // Generated by ComTest
 *
 */
@SuppressWarnings({ "all" })
public class RecursionBiggestTest {



  // Generated by ComTest BEGIN
  /** testHaeSuurin20 */
  @Test
  public void testHaeSuurin20() {    // RecursionBiggest: 20
    int[] t = { 1, 0, 0 } ; int n = 3; 
    assertEquals("From: RecursionBiggest line: 22", 1, haeSuurin(t, n)); 
    int[] t1 = { 0, 0, 9 } ; 
    assertEquals("From: RecursionBiggest line: 24", 9, haeSuurin(t1, n)); 
    int[] t2 = { 1, 3, 2 } ; 
    assertEquals("From: RecursionBiggest line: 26", 3, haeSuurin(t2, n)); 
    int[] t3 = { 0 } ; n = 1; 
    assertEquals("From: RecursionBiggest line: 28", 0, haeSuurin(t3, n)); 
    int[] t4 = { 2, 5, 2, 3, 5, 7, 7 } ; n = 7; 
    assertEquals("From: RecursionBiggest line: 30", 7, haeSuurin(t4, n)); 
  } // Generated by ComTest END
}